In [1]:
job_id = 'raw_openmiir_baseline'

In [2]:
import os
os.environ["THEANO_FLAGS"] = "floatX=float32,device=cpu"

base_selectors = dict()

SEED = 42
hdf5name = 'data/OpenMIIR-Perception-512Hz.hdf5'

# defaults
hyper_params = dict(
    only_1_inner_fold=False,  # FIXME this is only for dev

    classification_target_source='targets',
    
    ch_mean=False
)

In [3]:
import logging
logging.basicConfig(level=logging.INFO)
#logging.getLogger('deepthought.datasets').setLevel(logging.DEBUG) # debug dataset
log = logging.getLogger('deepthought')

import numpy as np
np.set_printoptions(precision=4)

In [4]:
from deepthought.experiments.encoding.datasets.openmiir import OpenMIIRNestedCVFoldGenerator
from deepthought.experiments.encoding.experiment_templates.svc_baseline import SVCBaseline

In [5]:
exp = SVCBaseline(job_id,
                  hdf5name,                                
                   OpenMIIRNestedCVFoldGenerator(),
                   hyper_params=hyper_params, default_params=None,
                   base_selectors=base_selectors)

exp.run(verbose=True)

# WindowsError: [Error 32] : 
# 'c:\\users\\zx305\\appdata\\local\\temp\\joblib_memmapping_folder_2468_8108094685\\2468-431670328-0a93642c5b024c169ad8fd707891d1d7.pkl'


running job #raw_openmiir_baseline
output path:  results\raw_openmiir_baseline


INFO:numexpr.utils:NumExpr defaulting to 8 threads.


processing outer fold {'train': ['P04', 'P06', 'P07', 'P09', 'P11', 'P12', 'P13', 'P14'], 'valid': ['P01']}
fold_scores for c=0.0100: [0.1979 0.1667 0.1562 0.1771 0.2708] mean=0.1938
fold_scores for c=0.0500: [0.1979 0.1667 0.1562 0.1771 0.2708] mean=0.1938
fold_scores for c=0.1000: [0.1979 0.1667 0.1562 0.1771 0.2708] mean=0.1938
fold_scores for c=0.0050: [0.1979 0.1667 0.1562 0.1771 0.2708] mean=0.1938
fold_scores for c=0.0010: [0.1979 0.1667 0.1562 0.1771 0.2708] mean=0.1938
fold_scores for c=0.0005: [0.1979 0.1667 0.1562 0.1771 0.2708] mean=0.1938
fold_scores for c=0.0001: [0.2083 0.1562 0.0938 0.1667 0.3021] mean=0.1854
fold_scores for c=0.5000: [0.1979 0.1667 0.1562 0.1771 0.2708] mean=0.1938
fold_scores for c=1.0000: [0.1979 0.1667 0.1562 0.1771 0.2708] mean=0.1938


d:\anacon\envs\python27\lib\site-packages\joblib\disk.py:122: UserWarning: Unable to delete folder c:\users\zx305\appdata\local\temp\joblib_memmapping_folder_2468_8108094685 after 5 tentatives.
  .format(folder_path, RM_SUBDIRS_N_RETRY))


WindowsError: [Error 32] : 'c:\\users\\zx305\\appdata\\local\\temp\\joblib_memmapping_folder_2468_8108094685\\2468-431670328-0a93642c5b024c169ad8fd707891d1d7.pkl'

In [ ]:

# SUMMARY for classifier linear_svc

# fold scores:  [ 0.25    0.1833  0.1     0.1333  0.2833  0.0833  0.2167  0.1833  0.2333]

#              precision    recall  f1-score   support

#         0.0       0.19      0.16      0.17        45
#         1.0       0.18      0.22      0.20        45
#         2.0       0.17      0.20      0.18        45
#         3.0       0.16      0.18      0.17        45
#         4.0       0.26      0.18      0.21        45
#         5.0       0.18      0.13      0.15        45
#         6.0       0.19      0.22      0.20        45
#         7.0       0.13      0.11      0.12        45
#         8.0       0.22      0.29      0.25        45
#         9.0       0.19      0.18      0.18        45
#        10.0       0.10      0.09      0.09        45
#        11.0       0.26      0.27      0.26        45

# avg / total       0.19      0.19      0.18       540

# [[ 7  4  7  5  3  4  6  1  1  1  1  5]
#  [ 1 10  1  7  0  6  1  4  5  3  6  1]
#  [ 3  1  9  1  3  4  5  3  5  3  8  0]
#  [ 1  3  2  8  5  2  2  7  4  4  2  5]
#  [ 5  3  4  3  8  2  1  2  5  4  2  6]
#  [ 5  8  3  6  1  6  3  2  3  3  2  3]
#  [ 1  2  5  1  3  2 10  7  6  1  2  5]
#  [ 5  5  4  8  1  3  3  5  3  4  3  1]
#  [ 2  5  2  1  3  2  6  1 13  5  2  3]
#  [ 0 10  5  3  2  2  3  2  5  8  5  0]
#  [ 3  6 10  4  0  1  5  1  3  3  4  5]
#  [ 3  0  2  2  2  0  8  3  5  3  5 12]]

# train accuracy: 0.999074074074
# test accuracy : 0.185185185185