In [1]:
job_id = 'raw_openmiir_baseline'

In [2]:
import os
os.environ["THEANO_FLAGS"] = "floatX=float32,device=cpu"

base_selectors = dict()

SEED = 42
hdf5name = 'data/OpenMIIR-Perception-512Hz.hdf5'

# defaults
hyper_params = dict(
    only_1_inner_fold=False,  # FIXME this is only for dev

    classification_target_source='targets',
    
    ch_mean=False
)

In [3]:
import logging
logging.basicConfig(level=logging.INFO)
#logging.getLogger('deepthought.datasets').setLevel(logging.DEBUG) # debug dataset
log = logging.getLogger('deepthought')

import numpy as np
np.set_printoptions(precision=4)

In [4]:
from deepthought.experiments.encoding.datasets.openmiir import OpenMIIRNestedCVFoldGenerator
from deepthought.experiments.encoding.experiment_templates.svc_baseline import SVCBaseline

In [5]:
exp = SVCBaseline(job_id, hdf5name,                                
                   OpenMIIRNestedCVFoldGenerator(),
                   hyper_params=hyper_params, default_params=None,
                   base_selectors=base_selectors)

exp.run(verbose=True)

running job #raw_openmiir_baseline
output path:  results\raw_openmiir_baseline


INFO:numexpr.utils:NumExpr defaulting to 8 threads.


processing outer fold {'train': ['P04', 'P06', 'P07', 'P09', 'P11', 'P12', 'P13', 'P14'], 'valid': ['P01']}
fold_scores for c=0.0100: [0.2188 0.1771 0.1562 0.1771 0.2396] mean=0.1938
fold_scores for c=0.0500: [0.2188 0.1771 0.1562 0.1771 0.2396] mean=0.1938


JoblibMemoryError: JoblibMemoryError
___________________________________________________________________________
...........................................................................
d:\anacon\envs\python27\lib\runpy.py in _run_module_as_main(mod_name='ipykernel_launcher', alter_argv=1)
    169     pkg_name = mod_name.rpartition('.')[0]
    170     main_globals = sys.modules["__main__"].__dict__
    171     if alter_argv:
    172         sys.argv[0] = fname
    173     return _run_code(code, main_globals, None,
--> 174                      "__main__", fname, loader, pkg_name)
        fname = r'C:\Users\zx305\AppData\Roaming\Python\Python27\site-packages\ipykernel_launcher.py'
        loader = <pkgutil.ImpLoader instance>
        pkg_name = ''
    175 
    176 def run_module(mod_name, init_globals=None,
    177                run_name=None, alter_sys=False):
    178     """Execute a module's code without importing it

...........................................................................
d:\anacon\envs\python27\lib\runpy.py in _run_code(code=<code object <module> at 000000000386F6B0, file ...n27\site-packages\ipykernel_launcher.py", line 5>, run_globals={'__builtins__': <module '__builtin__' (built-in)>, '__doc__': 'Entry point for launching an IPython kernel.\n\nTh...orts until\nafter removing the cwd from sys.path.\n', '__file__': r'C:\Users\zx305\AppData\Roaming\Python\Python27\site-packages\ipykernel_launcher.py', '__loader__': <pkgutil.ImpLoader instance>, '__name__': '__main__', '__package__': '', 'app': <module 'ipykernel.kernelapp' from 'C:\Users\zx3...\Python27\site-packages\ipykernel\kernelapp.pyc'>, 'sys': <module 'sys' (built-in)>}, init_globals=None, mod_name='__main__', mod_fname=r'C:\Users\zx305\AppData\Roaming\Python\Python27\site-packages\ipykernel_launcher.py', mod_loader=<pkgutil.ImpLoader instance>, pkg_name='')
     67         run_globals.update(init_globals)
     68     run_globals.update(__name__ = mod_name,
     69                        __file__ = mod_fname,
     70                        __loader__ = mod_loader,
     71                        __package__ = pkg_name)
---> 72     exec code in run_globals
        code = <code object <module> at 000000000386F6B0, file ...n27\site-packages\ipykernel_launcher.py", line 5>
        run_globals = {'__builtins__': <module '__builtin__' (built-in)>, '__doc__': 'Entry point for launching an IPython kernel.\n\nTh...orts until\nafter removing the cwd from sys.path.\n', '__file__': r'C:\Users\zx305\AppData\Roaming\Python\Python27\site-packages\ipykernel_launcher.py', '__loader__': <pkgutil.ImpLoader instance>, '__name__': '__main__', '__package__': '', 'app': <module 'ipykernel.kernelapp' from 'C:\Users\zx3...\Python27\site-packages\ipykernel\kernelapp.pyc'>, 'sys': <module 'sys' (built-in)>}
     73     return run_globals
     74 
     75 def _run_module_code(code, init_globals=None,
     76                     mod_name=None, mod_fname=None,

...........................................................................
C:\Users\zx305\AppData\Roaming\Python\Python27\site-packages\ipykernel_launcher.py in <module>()
     11     # This is added back by InteractiveShellApp.init_path()
     12     if sys.path[0] == '':
     13         del sys.path[0]
     14 
     15     from ipykernel import kernelapp as app
---> 16     app.launch_new_instance()

...........................................................................
C:\Users\zx305\AppData\Roaming\Python\Python27\site-packages\traitlets\config\application.py in launch_instance(cls=<class 'ipykernel.kernelapp.IPKernelApp'>, argv=None, **kwargs={})
    659 
    660         If a global instance already exists, this reinitializes and starts it
    661         """
    662         app = cls.instance(**kwargs)
    663         app.initialize(argv)
--> 664         app.start()
        app.start = <bound method IPKernelApp.start of <ipykernel.kernelapp.IPKernelApp object>>
    665 
    666 #-----------------------------------------------------------------------------
    667 # utility functions, for convenience
    668 #-----------------------------------------------------------------------------

...........................................................................
C:\Users\zx305\AppData\Roaming\Python\Python27\site-packages\ipykernel\kernelapp.py in start(self=<ipykernel.kernelapp.IPKernelApp object>)
    494         if self.poller is not None:
    495             self.poller.start()
    496         self.kernel.start()
    497         self.io_loop = ioloop.IOLoop.current()
    498         try:
--> 499             self.io_loop.start()
        self.io_loop.start = <bound method ZMQIOLoop.start of <zmq.eventloop.ioloop.ZMQIOLoop object>>
    500         except KeyboardInterrupt:
    501             pass
    502 
    503 launch_new_instance = IPKernelApp.launch_instance

...........................................................................
C:\Users\zx305\AppData\Roaming\Python\Python27\site-packages\tornado\ioloop.py in start(self=<zmq.eventloop.ioloop.ZMQIOLoop object>)
   1012                         self._timeouts = [x for x in self._timeouts
   1013                                           if x.callback is not None]
   1014                         heapq.heapify(self._timeouts)
   1015 
   1016                 for i in range(ncallbacks):
-> 1017                     self._run_callback(self._callbacks.popleft())
        self._run_callback = <bound method ZMQIOLoop._run_callback of <zmq.eventloop.ioloop.ZMQIOLoop object>>
        self._callbacks.popleft = <built-in method popleft of collections.deque object>
   1018                 for timeout in due_timeouts:
   1019                     if timeout.callback is not None:
   1020                         self._run_callback(timeout.callback)
   1021                 # Closures may be holding on to a lot of memory, so allow

...........................................................................
C:\Users\zx305\AppData\Roaming\Python\Python27\site-packages\tornado\ioloop.py in _run_callback(self=<zmq.eventloop.ioloop.ZMQIOLoop object>, callback=<functools.partial object>)
    753         """Runs a callback with error handling.
    754 
    755         For use in subclasses.
    756         """
    757         try:
--> 758             ret = callback()
        ret = undefined
        callback = <functools.partial object>
    759             if ret is not None:
    760                 from tornado import gen
    761                 # Functions that return Futures typically swallow all
    762                 # exceptions and store them in the Future.  If a Future

...........................................................................
C:\Users\zx305\AppData\Roaming\Python\Python27\site-packages\tornado\stack_context.py in null_wrapper(*args=(), **kwargs={})
    295         # Fast path when there are no active contexts.
    296         def null_wrapper(*args, **kwargs):
    297             try:
    298                 current_state = _state.contexts
    299                 _state.contexts = cap_contexts[0]
--> 300                 return fn(*args, **kwargs)
        args = ()
        kwargs = {}
    301             finally:
    302                 _state.contexts = current_state
    303         null_wrapper._wrapped = True
    304         return null_wrapper

...........................................................................
C:\Users\zx305\AppData\Roaming\Python\Python27\site-packages\zmq\eventloop\zmqstream.py in <lambda>()
    537             return
    538 
    539         if state & self.socket.events:
    540             # events still exist that haven't been processed
    541             # explicitly schedule handling to avoid missing events due to edge-triggered FDs
--> 542             self.io_loop.add_callback(lambda : self._handle_events(self.socket, 0))
    543 
    544     def _init_io_state(self):
    545         """initialize the ioloop event handler"""
    546         self.io_loop.add_handler(self.socket, self._handle_events, self.io_loop.READ)

...........................................................................
C:\Users\zx305\AppData\Roaming\Python\Python27\site-packages\zmq\eventloop\zmqstream.py in _handle_events(self=<zmq.eventloop.zmqstream.ZMQStream object>, fd=<zmq.sugar.socket.Socket object>, events=0)
    451             return
    452         zmq_events = self.socket.EVENTS
    453         try:
    454             # dispatch events:
    455             if zmq_events & zmq.POLLIN and self.receiving():
--> 456                 self._handle_recv()
        self._handle_recv = <bound method ZMQStream._handle_recv of <zmq.eventloop.zmqstream.ZMQStream object>>
    457                 if not self.socket:
    458                     return
    459             if zmq_events & zmq.POLLOUT and self.sending():
    460                 self._handle_send()

...........................................................................
C:\Users\zx305\AppData\Roaming\Python\Python27\site-packages\zmq\eventloop\zmqstream.py in _handle_recv(self=<zmq.eventloop.zmqstream.ZMQStream object>)
    481             else:
    482                 raise
    483         else:
    484             if self._recv_callback:
    485                 callback = self._recv_callback
--> 486                 self._run_callback(callback, msg)
        self._run_callback = <bound method ZMQStream._run_callback of <zmq.eventloop.zmqstream.ZMQStream object>>
        callback = <function null_wrapper>
        msg = [<zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>]
    487         
    488 
    489     def _handle_send(self):
    490         """Handle a send event."""

...........................................................................
C:\Users\zx305\AppData\Roaming\Python\Python27\site-packages\zmq\eventloop\zmqstream.py in _run_callback(self=<zmq.eventloop.zmqstream.ZMQStream object>, callback=<function null_wrapper>, *args=([<zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>],), **kwargs={})
    433         """Wrap running callbacks in try/except to allow us to
    434         close our socket."""
    435         try:
    436             # Use a NullContext to ensure that all StackContexts are run
    437             # inside our blanket exception handler rather than outside.
--> 438             callback(*args, **kwargs)
        callback = <function null_wrapper>
        args = ([<zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>],)
        kwargs = {}
    439         except:
    440             gen_log.error("Uncaught exception in ZMQStream callback",
    441                           exc_info=True)
    442             # Re-raise the exception so that IOLoop.handle_callback_exception

...........................................................................
C:\Users\zx305\AppData\Roaming\Python\Python27\site-packages\tornado\stack_context.py in null_wrapper(*args=([<zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>],), **kwargs={})
    295         # Fast path when there are no active contexts.
    296         def null_wrapper(*args, **kwargs):
    297             try:
    298                 current_state = _state.contexts
    299                 _state.contexts = cap_contexts[0]
--> 300                 return fn(*args, **kwargs)
        args = ([<zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>],)
        kwargs = {}
    301             finally:
    302                 _state.contexts = current_state
    303         null_wrapper._wrapped = True
    304         return null_wrapper

...........................................................................
C:\Users\zx305\AppData\Roaming\Python\Python27\site-packages\ipykernel\kernelbase.py in dispatcher(msg=[<zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>])
    278         if self.control_stream:
    279             self.control_stream.on_recv(self.dispatch_control, copy=False)
    280 
    281         def make_dispatcher(stream):
    282             def dispatcher(msg):
--> 283                 return self.dispatch_shell(stream, msg)
        msg = [<zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>]
    284             return dispatcher
    285 
    286         for s in self.shell_streams:
    287             s.on_recv(make_dispatcher(s), copy=False)

...........................................................................
C:\Users\zx305\AppData\Roaming\Python\Python27\site-packages\ipykernel\kernelbase.py in dispatch_shell(self=<ipykernel.ipkernel.IPythonKernel object>, stream=<zmq.eventloop.zmqstream.ZMQStream object>, msg={'buffers': [], 'content': {u'allow_stdin': True, u'code': u'exp = SVCBaseline(job_id, hdf5name,           ...lectors=base_selectors)\n\nexp.run(verbose=True)', u'silent': False, u'stop_on_error': True, u'store_history': True, u'user_expressions': {}}, 'header': {u'date': datetime.datetime(2020, 5, 20, 8, 54, 45, 415000, tzinfo=tzutc()), u'msg_id': u'1cdd763a98904e1d8a55e5259672f5ce', u'msg_type': u'execute_request', u'session': u'5ff694ce74404e4dbd6a5b85c14ae738', u'username': u'username', u'version': u'5.2'}, 'metadata': {}, 'msg_id': u'1cdd763a98904e1d8a55e5259672f5ce', 'msg_type': u'execute_request', 'parent_header': {}})
    228             self.log.warning("Unknown message type: %r", msg_type)
    229         else:
    230             self.log.debug("%s: %s", msg_type, msg)
    231             self.pre_handler_hook()
    232             try:
--> 233                 handler(stream, idents, msg)
        handler = <bound method IPythonKernel.execute_request of <ipykernel.ipkernel.IPythonKernel object>>
        stream = <zmq.eventloop.zmqstream.ZMQStream object>
        idents = ['5ff694ce74404e4dbd6a5b85c14ae738']
        msg = {'buffers': [], 'content': {u'allow_stdin': True, u'code': u'exp = SVCBaseline(job_id, hdf5name,           ...lectors=base_selectors)\n\nexp.run(verbose=True)', u'silent': False, u'stop_on_error': True, u'store_history': True, u'user_expressions': {}}, 'header': {u'date': datetime.datetime(2020, 5, 20, 8, 54, 45, 415000, tzinfo=tzutc()), u'msg_id': u'1cdd763a98904e1d8a55e5259672f5ce', u'msg_type': u'execute_request', u'session': u'5ff694ce74404e4dbd6a5b85c14ae738', u'username': u'username', u'version': u'5.2'}, 'metadata': {}, 'msg_id': u'1cdd763a98904e1d8a55e5259672f5ce', 'msg_type': u'execute_request', 'parent_header': {}}
    234             except Exception:
    235                 self.log.error("Exception in message handler:", exc_info=True)
    236             finally:
    237                 self.post_handler_hook()

...........................................................................
C:\Users\zx305\AppData\Roaming\Python\Python27\site-packages\ipykernel\kernelbase.py in execute_request(self=<ipykernel.ipkernel.IPythonKernel object>, stream=<zmq.eventloop.zmqstream.ZMQStream object>, ident=['5ff694ce74404e4dbd6a5b85c14ae738'], parent={'buffers': [], 'content': {u'allow_stdin': True, u'code': u'exp = SVCBaseline(job_id, hdf5name,           ...lectors=base_selectors)\n\nexp.run(verbose=True)', u'silent': False, u'stop_on_error': True, u'store_history': True, u'user_expressions': {}}, 'header': {u'date': datetime.datetime(2020, 5, 20, 8, 54, 45, 415000, tzinfo=tzutc()), u'msg_id': u'1cdd763a98904e1d8a55e5259672f5ce', u'msg_type': u'execute_request', u'session': u'5ff694ce74404e4dbd6a5b85c14ae738', u'username': u'username', u'version': u'5.2'}, 'metadata': {}, 'msg_id': u'1cdd763a98904e1d8a55e5259672f5ce', 'msg_type': u'execute_request', 'parent_header': {}})
    394         if not silent:
    395             self.execution_count += 1
    396             self._publish_execute_input(code, parent, self.execution_count)
    397 
    398         reply_content = self.do_execute(code, silent, store_history,
--> 399                                         user_expressions, allow_stdin)
        user_expressions = {}
        allow_stdin = True
    400 
    401         # Flush output before sending the reply.
    402         sys.stdout.flush()
    403         sys.stderr.flush()

...........................................................................
C:\Users\zx305\AppData\Roaming\Python\Python27\site-packages\ipykernel\ipkernel.py in do_execute(self=<ipykernel.ipkernel.IPythonKernel object>, code=u'exp = SVCBaseline(job_id, hdf5name,           ...lectors=base_selectors)\n\nexp.run(verbose=True)', silent=False, store_history=True, user_expressions={}, allow_stdin=True)
    203 
    204         self._forward_input(allow_stdin)
    205 
    206         reply_content = {}
    207         try:
--> 208             res = shell.run_cell(code, store_history=store_history, silent=silent)
        res = undefined
        shell.run_cell = <bound method ZMQInteractiveShell.run_cell of <ipykernel.zmqshell.ZMQInteractiveShell object>>
        code = u'exp = SVCBaseline(job_id, hdf5name,           ...lectors=base_selectors)\n\nexp.run(verbose=True)'
        store_history = True
        silent = False
    209         finally:
    210             self._restore_input()
    211 
    212         if res.error_before_exec is not None:

...........................................................................
C:\Users\zx305\AppData\Roaming\Python\Python27\site-packages\ipykernel\zmqshell.py in run_cell(self=<ipykernel.zmqshell.ZMQInteractiveShell object>, *args=(u'exp = SVCBaseline(job_id, hdf5name,           ...lectors=base_selectors)\n\nexp.run(verbose=True)',), **kwargs={'silent': False, 'store_history': True})
    532             )
    533         self.payload_manager.write_payload(payload)
    534 
    535     def run_cell(self, *args, **kwargs):
    536         self._last_traceback = None
--> 537         return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
        self.run_cell = <bound method ZMQInteractiveShell.run_cell of <ipykernel.zmqshell.ZMQInteractiveShell object>>
        args = (u'exp = SVCBaseline(job_id, hdf5name,           ...lectors=base_selectors)\n\nexp.run(verbose=True)',)
        kwargs = {'silent': False, 'store_history': True}
    538 
    539     def _showtraceback(self, etype, evalue, stb):
    540         # try to preserve ordering of tracebacks and print statements
    541         sys.stdout.flush()

...........................................................................
C:\Users\zx305\AppData\Roaming\Python\Python27\site-packages\IPython\core\interactiveshell.py in run_cell(self=<ipykernel.zmqshell.ZMQInteractiveShell object>, raw_cell=u'exp = SVCBaseline(job_id, hdf5name,           ...lectors=base_selectors)\n\nexp.run(verbose=True)', store_history=True, silent=False, shell_futures=True)
   2709                 self.displayhook.exec_result = result
   2710 
   2711                 # Execute the user code
   2712                 interactivity = "none" if silent else self.ast_node_interactivity
   2713                 has_raised = self.run_ast_nodes(code_ast.body, cell_name,
-> 2714                    interactivity=interactivity, compiler=compiler, result=result)
        interactivity = 'last_expr'
        compiler = <IPython.core.compilerop.CachingCompiler instance>
   2715                 
   2716                 self.last_execution_succeeded = not has_raised
   2717 
   2718                 # Reset this so later displayed values do not modify the

...........................................................................
C:\Users\zx305\AppData\Roaming\Python\Python27\site-packages\IPython\core\interactiveshell.py in run_ast_nodes(self=<ipykernel.zmqshell.ZMQInteractiveShell object>, nodelist=[<_ast.Assign object>, <_ast.Expr object>], cell_name='<ipython-input-5-3ecc01ba02a0>', interactivity='last', compiler=<IPython.core.compilerop.CachingCompiler instance>, result=<ExecutionResult object at 1862f630, execution_c..._before_exec=None error_in_exec=None result=None>)
   2819                     return True
   2820 
   2821             for i, node in enumerate(to_run_interactive):
   2822                 mod = ast.Interactive([node])
   2823                 code = compiler(mod, cell_name, "single")
-> 2824                 if self.run_code(code, result):
        self.run_code = <bound method ZMQInteractiveShell.run_code of <ipykernel.zmqshell.ZMQInteractiveShell object>>
        code = <code object <module> at 0000000015C5D530, file "<ipython-input-5-3ecc01ba02a0>", line 6>
        result = <ExecutionResult object at 1862f630, execution_c..._before_exec=None error_in_exec=None result=None>
   2825                     return True
   2826 
   2827             # Flush softspace
   2828             if softspace(sys.stdout, 0):

...........................................................................
C:\Users\zx305\AppData\Roaming\Python\Python27\site-packages\IPython\core\interactiveshell.py in run_code(self=<ipykernel.zmqshell.ZMQInteractiveShell object>, code_obj=<code object <module> at 0000000015C5D530, file "<ipython-input-5-3ecc01ba02a0>", line 6>, result=<ExecutionResult object at 1862f630, execution_c..._before_exec=None error_in_exec=None result=None>)
   2873         outflag = 1  # happens in more places, so it's easier as default
   2874         try:
   2875             try:
   2876                 self.hooks.pre_run_code_hook()
   2877                 #rprint('Running code', repr(code_obj)) # dbg
-> 2878                 exec(code_obj, self.user_global_ns, self.user_ns)
        code_obj = <code object <module> at 0000000015C5D530, file "<ipython-input-5-3ecc01ba02a0>", line 6>
        self.user_global_ns = {'In': ['', u"job_id = 'raw_openmiir_baseline'", u'import os\nos.environ["THEANO_FLAGS"] = "float..._source=\'targets\',\n    \n    ch_mean=False\n)', u"import logging\nlogging.basicConfig(level=logg...rt numpy as np\nnp.set_printoptions(precision=4)", u'from deepthought.experiments.encoding.datasets...riment_templates.svc_baseline import SVCBaseline', u'exp = SVCBaseline(job_id, hdf5name,           ...lectors=base_selectors)\n\nexp.run(verbose=True)'], 'OpenMIIRNestedCVFoldGenerator': <class 'deepthought.experiments.encoding.datasets.openmiir.OpenMIIRNestedCVFoldGenerator'>, 'Out': {}, 'SEED': 42, 'SVCBaseline': <class 'deepthought.experiments.encoding.experiment_templates.svc_baseline.SVCBaseline'>, '_': '', '__': '', '___': '', '__builtin__': <module '__builtin__' (built-in)>, '__builtins__': <module '__builtin__' (built-in)>, ...}
        self.user_ns = {'In': ['', u"job_id = 'raw_openmiir_baseline'", u'import os\nos.environ["THEANO_FLAGS"] = "float..._source=\'targets\',\n    \n    ch_mean=False\n)', u"import logging\nlogging.basicConfig(level=logg...rt numpy as np\nnp.set_printoptions(precision=4)", u'from deepthought.experiments.encoding.datasets...riment_templates.svc_baseline import SVCBaseline', u'exp = SVCBaseline(job_id, hdf5name,           ...lectors=base_selectors)\n\nexp.run(verbose=True)'], 'OpenMIIRNestedCVFoldGenerator': <class 'deepthought.experiments.encoding.datasets.openmiir.OpenMIIRNestedCVFoldGenerator'>, 'Out': {}, 'SEED': 42, 'SVCBaseline': <class 'deepthought.experiments.encoding.experiment_templates.svc_baseline.SVCBaseline'>, '_': '', '__': '', '___': '', '__builtin__': <module '__builtin__' (built-in)>, '__builtins__': <module '__builtin__' (built-in)>, ...}
   2879             finally:
   2880                 # Reset our crash handler in place
   2881                 sys.excepthook = old_excepthook
   2882         except SystemExit as e:

...........................................................................
E:\360MoveData\Users\zx305\Documents\GitHub\openmiir-rl-2016\<ipython-input-5-3ecc01ba02a0> in <module>()
      1 exp = SVCBaseline(job_id, hdf5name,                                
      2                    OpenMIIRNestedCVFoldGenerator(),
      3                    hyper_params=hyper_params, default_params=None,
      4                    base_selectors=base_selectors)
      5 
----> 6 exp.run(verbose=True)

...........................................................................
E:\360MoveData\Users\zx305\Documents\GitHub\openmiir-rl-2016\deepthought\experiments\encoding\experiment_templates\svc_baseline.py in run(self=<deepthought.experiments.encoding.experiment_templates.svc_baseline.SVCBaseline object>, verbose=True)
     28 
     29         return dummy_encoder_fn
     30 
     31     def run(self, verbose=False):
     32         from deepthought.experiments.encoding.classifiers.linear_svc import LinearSVCClassifierFactory
---> 33         super(SVCBaseline, self).run(classifiers=(('linear_svc', LinearSVCClassifierFactory()),), verbose=verbose)
        self.run = <bound method SVCBaseline.run of <deepthought.ex...iment_templates.svc_baseline.SVCBaseline object>>
        LinearSVCClassifierFactory = <class 'deepthought.experiments.encoding.classifiers.linear_svc.LinearSVCClassifierFactory'>
        verbose = True

...........................................................................
E:\360MoveData\Users\zx305\Documents\GitHub\openmiir-rl-2016\deepthought\experiments\encoding\experiment_templates\base.py in run(self=<deepthought.experiments.encoding.experiment_templates.svc_baseline.SVCBaseline object>, classifiers=(('linear_svc', <deepthought.experiments.encoding.classifiers.linear_svc.LinearSVCClassifierFactory object>),), verbose=True, debug=False)
    166 
    167                 if debug:
    168                     print idx_folds  # print the generated folds before running the classifier
    169                 
    170                 # train classifier
--> 171                 classifier, predict_fn = classifier_factory.train(X_train, Y_train, idx_folds, self.hyper_params, model_prefix)
        classifier = undefined
        predict_fn = undefined
        classifier_factory.train = <bound method LinearSVCClassifierFactory.train o...rs.linear_svc.LinearSVCClassifierFactory object>>
        X_train = array([[-0.0576, -0.0839, -0.1115, ...,  0.0635,... 0.024 ,  0.0389,  0.0469]],
      dtype=float32)
        Y_train = array([ 0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  ... 10, 10, 11,
       11, 11, 11, 11], dtype=int64)
        idx_folds = [([1, 2, 3, 4, 6, 7, 8, 9, 11, 12, 13, 14, 16, 17, 18, 19, 21, 22, 23, 24, ...], [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, ...]), ([0, 2, 3, 4, 5, 7, 8, 9, 10, 12, 13, 14, 15, 17, 18, 19, 20, 22, 23, 24, ...], [1, 6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86, 91, 96, ...]), ([0, 1, 3, 4, 5, 6, 8, 9, 10, 11, 13, 14, 15, 16, 18, 19, 20, 21, 23, 24, ...], [2, 7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57, 62, 67, 72, 77, 82, 87, 92, 97, ...]), ([0, 1, 2, 4, 5, 6, 7, 9, 10, 11, 12, 14, 15, 16, 17, 19, 20, 21, 22, 24, ...], [3, 8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58, 63, 68, 73, 78, 83, 88, 93, 98, ...]), ([0, 1, 2, 3, 5, 6, 7, 8, 10, 11, 12, 13, 15, 16, 17, 18, 20, 21, 22, 23, ...], [4, 9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84, 89, 94, 99, ...])]
        self.hyper_params = {'ch_mean': False, 'classification_target_source': 'targets', 'only_1_inner_fold': False, 'pretrain_target_source': 'targets'}
        model_prefix = r'results\raw_openmiir_baseline\linear_svc_fold_0'
    172 
    173                 # test classifier
    174                 train_Y_pred = predict_fn(X_train)
    175                 test_Y_pred = predict_fn(X_test)

...........................................................................
E:\360MoveData\Users\zx305\Documents\GitHub\openmiir-rl-2016\deepthought\experiments\encoding\classifiers\linear_svc.py in train(self=<deepthought.experiments.encoding.classifiers.linear_svc.LinearSVCClassifierFactory object>, X=array([[-0.0576, -0.0839, -0.1115, ...,  0.0635,... 0.024 ,  0.0389,  0.0469]],
      dtype=float32), Y=array([ 0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  ... 10, 10, 11,
       11, 11, 11, 11], dtype=int64), idx_folds=[([1, 2, 3, 4, 6, 7, 8, 9, 11, 12, 13, 14, 16, 17, 18, 19, 21, 22, 23, 24, ...], [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, ...]), ([0, 2, 3, 4, 5, 7, 8, 9, 10, 12, 13, 14, 15, 17, 18, 19, 20, 22, 23, 24, ...], [1, 6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86, 91, 96, ...]), ([0, 1, 3, 4, 5, 6, 8, 9, 10, 11, 13, 14, 15, 16, 18, 19, 20, 21, 23, 24, ...], [2, 7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57, 62, 67, 72, 77, 82, 87, 92, 97, ...]), ([0, 1, 2, 4, 5, 6, 7, 9, 10, 11, 12, 14, 15, 16, 17, 19, 20, 21, 22, 24, ...], [3, 8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58, 63, 68, 73, 78, 83, 88, 93, 98, ...]), ([0, 1, 2, 3, 5, 6, 7, 8, 10, 11, 12, 13, 15, 16, 17, 18, 20, 21, 22, 23, ...], [4, 9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84, 89, 94, 99, ...])], hyper_params={'ch_mean': False, 'classification_target_source': 'targets', 'only_1_inner_fold': False, 'pretrain_target_source': 'targets'}, model_prefix=r'results\raw_openmiir_baseline\linear_svc_fold_0', verbose=False)
     39             c_values = [0.01, 0.05, 0.1, 0.005, 0.001, 0.0005, 0.0001, 0.5, 1, 2]
     40         self.c_values = c_values
     41     
     42     def train(self, X, Y, idx_folds, hyper_params, model_prefix, verbose=False):
     43         # get best c through another round of cross-validation        
---> 44         best_c = get_best_c(X, Y, idx_folds, self.c_values)
        best_c = undefined
        X = array([[-0.0576, -0.0839, -0.1115, ...,  0.0635,... 0.024 ,  0.0389,  0.0469]],
      dtype=float32)
        Y = array([ 0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  ... 10, 10, 11,
       11, 11, 11, 11], dtype=int64)
        idx_folds = [([1, 2, 3, 4, 6, 7, 8, 9, 11, 12, 13, 14, 16, 17, 18, 19, 21, 22, 23, 24, ...], [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, ...]), ([0, 2, 3, 4, 5, 7, 8, 9, 10, 12, 13, 14, 15, 17, 18, 19, 20, 22, 23, 24, ...], [1, 6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86, 91, 96, ...]), ([0, 1, 3, 4, 5, 6, 8, 9, 10, 11, 13, 14, 15, 16, 18, 19, 20, 21, 23, 24, ...], [2, 7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57, 62, 67, 72, 77, 82, 87, 92, 97, ...]), ([0, 1, 2, 4, 5, 6, 7, 9, 10, 11, 12, 14, 15, 16, 17, 19, 20, 21, 22, 24, ...], [3, 8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58, 63, 68, 73, 78, 83, 88, 93, 98, ...]), ([0, 1, 2, 3, 5, 6, 7, 8, 10, 11, 12, 13, 15, 16, 17, 18, 20, 21, 22, 23, ...], [4, 9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84, 89, 94, 99, ...])]
        self.c_values = [0.01, 0.05, 0.1, 0.005, 0.001, 0.0005, 0.0001, 0.5, 1, 2]
     45         classifier = SVC(kernel='linear', C=best_c).fit(X, Y)
     46         return classifier, classifier.predict
     47 
     48     

...........................................................................
E:\360MoveData\Users\zx305\Documents\GitHub\openmiir-rl-2016\deepthought\experiments\encoding\classifiers\linear_svc.py in get_best_c(X=array([[-0.0576, -0.0839, -0.1115, ...,  0.0635,... 0.024 ,  0.0389,  0.0469]],
      dtype=float32), Y=array([ 0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  ... 10, 10, 11,
       11, 11, 11, 11], dtype=int64), folds=[([1, 2, 3, 4, 6, 7, 8, 9, 11, 12, 13, 14, 16, 17, 18, 19, 21, 22, 23, 24, ...], [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, ...]), ([0, 2, 3, 4, 5, 7, 8, 9, 10, 12, 13, 14, 15, 17, 18, 19, 20, 22, 23, 24, ...], [1, 6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86, 91, 96, ...]), ([0, 1, 3, 4, 5, 6, 8, 9, 10, 11, 13, 14, 15, 16, 18, 19, 20, 21, 23, 24, ...], [2, 7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57, 62, 67, 72, 77, 82, 87, 92, 97, ...]), ([0, 1, 2, 4, 5, 6, 7, 9, 10, 11, 12, 14, 15, 16, 17, 19, 20, 21, 22, 24, ...], [3, 8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58, 63, 68, 73, 78, 83, 88, 93, 98, ...]), ([0, 1, 2, 3, 5, 6, 7, 8, 10, 11, 12, 13, 15, 16, 17, 18, 20, 21, 22, 23, ...], [4, 9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84, 89, 94, 99, ...])], c_values=[0.01, 0.05, 0.1, 0.005, 0.001, 0.0005, 0.0001, 0.5, 1, 2], n_jobs=10)
     18     for c in c_values:
     19         # parallel version
     20         from joblib import Parallel, delayed
     21 
     22         fold_scores = Parallel(n_jobs=n_jobs)(delayed(get_fold_score)
---> 23                                               (X, Y, fold, c) for fold in folds)
        X = array([[-0.0576, -0.0839, -0.1115, ...,  0.0635,... 0.024 ,  0.0389,  0.0469]],
      dtype=float32)
        Y = array([ 0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  ... 10, 10, 11,
       11, 11, 11, 11], dtype=int64)
        folds = [([1, 2, 3, 4, 6, 7, 8, 9, 11, 12, 13, 14, 16, 17, 18, 19, 21, 22, 23, 24, ...], [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, ...]), ([0, 2, 3, 4, 5, 7, 8, 9, 10, 12, 13, 14, 15, 17, 18, 19, 20, 22, 23, 24, ...], [1, 6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86, 91, 96, ...]), ([0, 1, 3, 4, 5, 6, 8, 9, 10, 11, 13, 14, 15, 16, 18, 19, 20, 21, 23, 24, ...], [2, 7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57, 62, 67, 72, 77, 82, 87, 92, 97, ...]), ([0, 1, 2, 4, 5, 6, 7, 9, 10, 11, 12, 14, 15, 16, 17, 19, 20, 21, 22, 24, ...], [3, 8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58, 63, 68, 73, 78, 83, 88, 93, 98, ...]), ([0, 1, 2, 3, 5, 6, 7, 8, 10, 11, 12, 13, 15, 16, 17, 18, 20, 21, 22, 23, ...], [4, 9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84, 89, 94, 99, ...])]
     24 
     25         fold_scores = np.asarray(fold_scores)
     26         print 'fold_scores for c={:.4f}: {} mean={:.4f}'.format(c, fold_scores, fold_scores.mean())
     27         c_scores.append(np.mean(fold_scores))

...........................................................................
d:\anacon\envs\python27\lib\site-packages\joblib\parallel.py in __call__(self=Parallel(n_jobs=10), iterable=<generator object <genexpr>>)
   1012                 # No need to wait for async callbacks to trigger to
   1013                 # consumption.
   1014                 self._iterating = False
   1015 
   1016             with self._backend.retrieval_context():
-> 1017                 self.retrieve()
        self.retrieve = <bound method Parallel.retrieve of Parallel(n_jobs=10)>
   1018             # Make sure that we get a last message telling us we are done
   1019             elapsed_time = time.time() - self._start_time
   1020             self._print('Done %3i out of %3i | elapsed: %s finished',
   1021                         (len(self._output), len(self._output),

---------------------------------------------------------------------------
Joblib worker traceback:
---------------------------------------------------------------------------
MemoryError                                        Wed May 20 17:04:09 2020
PID: 8968                 Python 2.7.15: d:\anacon\envs\python27\python.exe
...........................................................................
d:\anacon\envs\python27\lib\site-packages\joblib\parallel.py in __call__(self=<joblib.parallel.BatchedCalls object>)
    251     def __call__(self):
    252         # Set the default nested backend to self._backend but do not set the
    253         # change the default number of processes to -1
    254         with parallel_backend(self._backend, n_jobs=self._n_jobs):
    255             return [func(*args, **kwargs)
--> 256                     for func, args, kwargs in self.items]
        func = <function get_fold_score>
        args = (memmap([[-0.05758746, -0.08387283, -0.11154795, ...        0.03891791,  0.0469382 ]], dtype=float32), array([ 0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  ... 10, 10, 11,
       11, 11, 11, 11], dtype=int64), ([1, 2, 3, 4, 6, 7, 8, 9, 11, 12, 13, 14, 16, 17, 18, 19, 21, 22, 23, 24, ...], [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, ...]), 0.1)
        kwargs = {}
        self.items = [(<function get_fold_score>, (memmap([[-0.05758746, -0.08387283, -0.11154795, ...        0.03891791,  0.0469382 ]], dtype=float32), array([ 0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  ... 10, 10, 11,
       11, 11, 11, 11], dtype=int64), ([1, 2, 3, 4, 6, 7, 8, 9, 11, 12, 13, 14, 16, 17, 18, 19, 21, 22, 23, 24, ...], [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, ...]), 0.1), {})]
    257 
    258     def __len__(self):
    259         return self._size
    260 

...........................................................................
E:\360MoveData\Users\zx305\Documents\GitHub\openmiir-rl-2016\deepthought\experiments\encoding\classifiers\linear_svc.py in get_fold_score(X=memmap([[-0.05758746, -0.08387283, -0.11154795, ...        0.03891791,  0.0469382 ]], dtype=float32), Y=array([ 0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  ... 10, 10, 11,
       11, 11, 11, 11], dtype=int64), fold=([1, 2, 3, 4, 6, 7, 8, 9, 11, 12, 13, 14, 16, 17, 18, 19, 21, 22, 23, 24, ...], [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, ...]), c=0.1)
      4 from base import ClassifierFactory
      5 
      6 
      7 def get_fold_score(X, Y, fold, c):
      8     train_idx, valid_idx = fold
----> 9     model = SVC(kernel='linear', C=c).fit(X[train_idx], Y[train_idx])
        model = undefined
        c.fit = undefined
        X = memmap([[-0.05758746, -0.08387283, -0.11154795, ...        0.03891791,  0.0469382 ]], dtype=float32)
        train_idx = [1, 2, 3, 4, 6, 7, 8, 9, 11, 12, 13, 14, 16, 17, 18, 19, 21, 22, 23, 24, ...]
        Y = array([ 0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  ... 10, 10, 11,
       11, 11, 11, 11], dtype=int64)
     10 
     11     if len(valid_idx) > 0:
     12         return model.score(X[valid_idx], Y[valid_idx])
     13     else:

...........................................................................
d:\anacon\envs\python27\lib\site-packages\sklearn\svm\base.py in fit(self=SVC(C=0.1, cache_size=200, class_weight=None, co...None,
  shrinking=True, tol=0.001, verbose=False), X=array([[ 0.06734115,  0.08545426,  0.10274516, ....  0.02397073,
         0.03891791,  0.0469382 ]]), y=array([ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  ..., 10.,
       10., 10., 10., 11., 11., 11., 11.]), sample_weight=array([], dtype=float64))
    173         if self.gamma in ('scale', 'auto_deprecated'):
    174             if sparse:
    175                 # var = E[X^2] - E[X]^2
    176                 X_var = (X.multiply(X)).mean() - (X.mean()) ** 2
    177             else:
--> 178                 X_var = X.var()
        X_var = undefined
        X.var = <built-in method var of numpy.ndarray object>
    179             if self.gamma == 'scale':
    180                 if X_var != 0:
    181                     self._gamma = 1.0 / (X.shape[1] * X_var)
    182                 else:

...........................................................................
d:\anacon\envs\python27\lib\site-packages\numpy\core\_methods.py in _var(a=array([[ 0.06734115,  0.08545426,  0.10274516, ....  0.02397073,
         0.03891791,  0.0469382 ]]), axis=None, dtype=None, out=None, ddof=0, keepdims=False)
    112         arrmean = arrmean.dtype.type(arrmean / rcount)
    113 
    114     # Compute sum of squared deviations from mean
    115     # Note that x may not be inexact and that we need it to be an array,
    116     # not a scalar.
--> 117     x = asanyarray(arr - arrmean)
        x = undefined
        arr = array([[ 0.06734115,  0.08545426,  0.10274516, ....  0.02397073,
         0.03891791,  0.0469382 ]])
        arrmean = array([[-9.05818399e-05]])
    118     if issubclass(arr.dtype.type, nt.complexfloating):
    119         x = um.multiply(x, um.conjugate(x), out=x).real
    120     else:
    121         x = um.multiply(x, x, out=x)

MemoryError: 
___________________________________________________________________________

In [ ]:
## 原先的输出

# running job #raw_openmiir_baseline
# output path:  results/raw_openmiir_baseline
# processing outer fold {'train': ['P04', 'P06', 'P07', 'P09', 'P11', 'P12', 'P13', 'P14'], 'valid': ['P01']}
# fold_scores for c=0.0100: [ 0.2188  0.1771  0.1562  0.1771  0.2396] mean=0.1938
# fold_scores for c=0.0500: [ 0.2188  0.1771  0.1562  0.1771  0.2396] mean=0.1938
# fold_scores for c=0.1000: [ 0.2188  0.1771  0.1562  0.1771  0.2396] mean=0.1938
# fold_scores for c=0.0050: [ 0.2188  0.1771  0.1562  0.1771  0.2396] mean=0.1938
# fold_scores for c=0.0010: [ 0.2188  0.1771  0.1562  0.1771  0.2396] mean=0.1938
# fold_scores for c=0.0005: [ 0.2188  0.1771  0.1562  0.1771  0.2396] mean=0.1938
# fold_scores for c=0.0001: [ 0.2292  0.1667  0.125   0.1979  0.2708] mean=0.1979
# fold_scores for c=0.5000: [ 0.2188  0.1771  0.1562  0.1771  0.2396] mean=0.1938
# fold_scores for c=1.0000: [ 0.2188  0.1771  0.1562  0.1771  0.2396] mean=0.1938
# fold_scores for c=2.0000: [ 0.2188  0.1771  0.1562  0.1771  0.2396] mean=0.1938
# best c=0.0001 with score 0.197916666667
# linear_svc results for fold {'train': ['P04', 'P06', 'P07', 'P09', 'P11', 'P12', 'P13', 'P14'], 'valid': ['P01']}
#              precision    recall  f1-score   support

#           0       0.00      0.00      0.00         5
#           1       0.12      0.20      0.15         5
#           2       0.17      0.20      0.18         5
#           3       0.60      0.60      0.60         5
#           4       0.50      0.40      0.44         5
#           5       0.00      0.00      0.00         5
#           6       0.12      0.20      0.15         5
#           7       1.00      0.20      0.33         5
#           8       0.50      0.40      0.44         5
#           9       0.00      0.00      0.00         5
#          10       0.12      0.20      0.15         5
#          11       0.50      0.60      0.55         5

# avg / total       0.30      0.25      0.25        60

# [[0 1 1 0 0 0 1 0 0 1 0 1]
#  [1 1 0 0 0 0 0 0 0 0 3 0]
#  [1 0 1 0 0 0 0 0 0 1 2 0]
#  [0 0 0 3 0 0 1 0 0 0 0 1]
#  [3 0 0 0 2 0 0 0 0 0 0 0]
#  [1 3 0 0 0 0 0 0 1 0 0 0]
#  [0 0 1 0 1 0 1 0 1 0 1 0]
#  [0 0 0 1 0 1 1 1 0 0 1 0]
#  [0 1 1 0 0 0 1 0 2 0 0 0]
#  [0 2 1 0 1 0 1 0 0 0 0 0]
#  [1 0 1 1 0 0 0 0 0 0 1 1]
#  [0 0 0 0 0 0 2 0 0 0 0 3]]
# overall test accuracy so far: 0.25
# processing outer fold {'train': ['P01', 'P06', 'P07', 'P09', 'P11', 'P12', 'P13', 'P14'], 'valid': ['P04']}
# fold_scores for c=0.0100: [ 0.1771  0.1667  0.2292  0.1875  0.2396] mean=0.2000
# fold_scores for c=0.0500: [ 0.1771  0.1667  0.2292  0.1875  0.2396] mean=0.2000
# fold_scores for c=0.1000: [ 0.1771  0.1667  0.2292  0.1875  0.2396] mean=0.2000
# fold_scores for c=0.0050: [ 0.1771  0.1667  0.2292  0.1875  0.2396] mean=0.2000
# fold_scores for c=0.0010: [ 0.1771  0.1667  0.2292  0.1875  0.2396] mean=0.2000
# fold_scores for c=0.0005: [ 0.1771  0.1667  0.2292  0.1875  0.2396] mean=0.2000
# fold_scores for c=0.0001: [ 0.1771  0.1667  0.1875  0.1875  0.25  ] mean=0.1938
# fold_scores for c=0.5000: [ 0.1771  0.1667  0.2292  0.1875  0.2396] mean=0.2000
# fold_scores for c=1.0000: [ 0.1771  0.1667  0.2292  0.1875  0.2396] mean=0.2000
# fold_scores for c=2.0000: [ 0.1771  0.1667  0.2292  0.1875  0.2396] mean=0.2000
# best c=0.01 with score 0.2
# linear_svc results for fold {'train': ['P01', 'P06', 'P07', 'P09', 'P11', 'P12', 'P13', 'P14'], 'valid': ['P04']}
#              precision    recall  f1-score   support

#           0       0.20      0.20      0.20         5
#           1       0.33      0.40      0.36         5
#           2       0.12      0.20      0.15         5
#           3       0.00      0.00      0.00         5
#           4       0.00      0.00      0.00         5
#           5       0.00      0.00      0.00         5
#           6       0.22      0.40      0.29         5
#           7       0.17      0.20      0.18         5
#           8       0.29      0.40      0.33         5
#           9       0.25      0.20      0.22         5
#          10       0.00      0.00      0.00         5
#          11       0.17      0.20      0.18         5

# avg / total       0.15      0.18      0.16        60

# [[1 0 1 0 0 0 2 0 0 0 0 1]
#  [0 2 0 1 0 1 0 1 0 0 0 0]
#  [1 0 1 0 0 0 1 0 0 1 1 0]
#  [0 1 1 0 0 0 0 0 1 0 0 2]
#  [1 0 0 0 0 1 1 1 1 0 0 0]
#  [0 0 1 1 0 0 0 1 1 1 0 0]
#  [0 1 1 0 0 0 2 0 0 0 0 1]
#  [2 0 0 1 0 0 0 1 1 0 0 0]
#  [0 0 0 0 0 0 1 0 2 1 0 1]
#  [0 1 1 0 0 0 0 0 1 1 1 0]
#  [0 1 2 0 0 1 1 0 0 0 0 0]
#  [0 0 0 0 0 0 1 2 0 0 1 1]]
# overall test accuracy so far: 0.216666666667
# processing outer fold {'train': ['P01', 'P04', 'P07', 'P09', 'P11', 'P12', 'P13', 'P14'], 'valid': ['P06']}
# /home/stober/.local/lib/python2.7/site-packages/sklearn/metrics/classification.py:958: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
#   'precision', 'predicted', average, warn_for)
# fold_scores for c=0.0100: [ 0.2083  0.1979  0.1979  0.1354  0.2604] mean=0.2000
# fold_scores for c=0.0500: [ 0.2083  0.1979  0.1979  0.1354  0.2604] mean=0.2000
# fold_scores for c=0.1000: [ 0.2083  0.1979  0.1979  0.1354  0.2604] mean=0.2000
# fold_scores for c=0.0050: [ 0.2083  0.1979  0.1979  0.1354  0.2604] mean=0.2000
# fold_scores for c=0.0010: [ 0.2083  0.1979  0.1979  0.1354  0.2604] mean=0.2000
# fold_scores for c=0.0005: [ 0.2083  0.1979  0.1979  0.1354  0.2604] mean=0.2000
# fold_scores for c=0.0001: [ 0.1771  0.2292  0.1979  0.1667  0.2188] mean=0.1979
# fold_scores for c=0.5000: [ 0.2083  0.1979  0.1979  0.1354  0.2604] mean=0.2000
# fold_scores for c=1.0000: [ 0.2083  0.1979  0.1979  0.1354  0.2604] mean=0.2000
# fold_scores for c=2.0000: [ 0.2083  0.1979  0.1979  0.1354  0.2604] mean=0.2000
# best c=0.01 with score 0.2
# linear_svc results for fold {'train': ['P01', 'P04', 'P07', 'P09', 'P11', 'P12', 'P13', 'P14'], 'valid': ['P06']}
#              precision    recall  f1-score   support

#           0       0.00      0.00      0.00         5
#           1       0.00      0.00      0.00         5
#           2       0.00      0.00      0.00         5
#           3       0.00      0.00      0.00         5
#           4       0.00      0.00      0.00         5
#           5       0.33      0.20      0.25         5
#           6       0.50      0.40      0.44         5
#           7       0.10      0.20      0.13         5
#           8       0.14      0.20      0.17         5
#           9       0.14      0.20      0.17         5
#          10       0.00      0.00      0.00         5
#          11       0.00      0.00      0.00         5

# avg / total       0.10      0.10      0.10        60

# [[0 0 0 1 2 1 1 0 0 0 0 0]
#  [0 0 0 1 0 0 0 2 1 0 1 0]
#  [1 1 0 0 0 1 0 0 1 0 1 0]
#  [0 0 0 0 2 0 0 2 0 1 0 0]
#  [0 1 0 1 0 0 0 0 1 1 0 1]
#  [0 1 0 0 0 1 1 1 0 0 0 1]
#  [1 0 0 1 0 0 2 0 0 0 1 0]
#  [0 0 2 0 0 0 0 1 0 2 0 0]
#  [0 1 0 0 1 0 0 1 1 1 0 0]
#  [0 1 0 0 0 0 0 2 1 1 0 0]
#  [0 0 1 0 0 0 0 1 2 1 0 0]
#  [2 0 0 0 2 0 0 0 0 0 1 0]]
# overall test accuracy so far: 0.177777777778
# processing outer fold {'train': ['P01', 'P04', 'P06', 'P09', 'P11', 'P12', 'P13', 'P14'], 'valid': ['P07']}
# fold_scores for c=0.0100: [ 0.1875  0.2188  0.1771  0.1667  0.25  ] mean=0.2000
# fold_scores for c=0.0500: [ 0.1875  0.2188  0.1771  0.1667  0.25  ] mean=0.2000
# fold_scores for c=0.1000: [ 0.1875  0.2188  0.1771  0.1667  0.25  ] mean=0.2000
# fold_scores for c=0.0050: [ 0.1875  0.2188  0.1771  0.1667  0.25  ] mean=0.2000
# fold_scores for c=0.0010: [ 0.1875  0.2188  0.1771  0.1667  0.25  ] mean=0.2000
# fold_scores for c=0.0005: [ 0.1875  0.2188  0.1771  0.1667  0.25  ] mean=0.2000
# fold_scores for c=0.0001: [ 0.1979  0.1979  0.1667  0.1875  0.25  ] mean=0.2000
# fold_scores for c=0.5000: [ 0.1875  0.2188  0.1771  0.1667  0.25  ] mean=0.2000
# fold_scores for c=1.0000: [ 0.1875  0.2188  0.1771  0.1667  0.25  ] mean=0.2000
# fold_scores for c=2.0000: [ 0.1875  0.2188  0.1771  0.1667  0.25  ] mean=0.2000
# best c=0.01 with score 0.2
# linear_svc results for fold {'train': ['P01', 'P04', 'P06', 'P09', 'P11', 'P12', 'P13', 'P14'], 'valid': ['P07']}
#              precision    recall  f1-score   support

#           0       0.00      0.00      0.00         5
#           1       0.00      0.00      0.00         5
#           2       0.25      0.20      0.22         5
#           3       0.00      0.00      0.00         5
#           4       0.17      0.20      0.18         5
#           5       0.25      0.20      0.22         5
#           6       0.00      0.00      0.00         5
#           7       0.33      0.20      0.25         5
#           8       0.09      0.20      0.13         5
#           9       0.25      0.20      0.22         5
#          10       0.14      0.20      0.17         5
#          11       0.17      0.20      0.18         5

# avg / total       0.14      0.13      0.13        60

# [[0 0 1 0 1 0 0 0 0 0 1 2]
#  [0 0 0 2 0 0 0 0 2 1 0 0]
#  [0 0 1 1 0 1 0 1 1 0 0 0]
#  [0 0 0 0 2 0 1 0 0 1 1 0]
#  [0 0 1 1 1 0 0 0 1 0 1 0]
#  [2 1 0 1 0 1 0 0 0 0 0 0]
#  [0 0 0 0 0 1 0 1 2 0 0 1]
#  [0 0 0 0 1 1 1 1 1 0 0 0]
#  [0 0 1 0 1 0 1 0 1 0 1 0]
#  [0 1 0 1 0 0 0 0 0 1 2 0]
#  [0 0 0 0 0 0 1 0 1 0 1 2]
#  [0 0 0 1 0 0 0 0 2 1 0 1]]
# overall test accuracy so far: 0.166666666667
# processing outer fold {'train': ['P01', 'P04', 'P06', 'P07', 'P11', 'P12', 'P13', 'P14'], 'valid': ['P09']}
# fold_scores for c=0.0100: [ 0.1667  0.1562  0.1667  0.1875  0.2292] mean=0.1812
# fold_scores for c=0.0500: [ 0.1667  0.1562  0.1667  0.1875  0.2292] mean=0.1812
# fold_scores for c=0.1000: [ 0.1667  0.1562  0.1667  0.1875  0.2292] mean=0.1812
# fold_scores for c=0.0050: [ 0.1667  0.1562  0.1667  0.1875  0.2292] mean=0.1812
# fold_scores for c=0.0010: [ 0.1667  0.1562  0.1667  0.1875  0.2292] mean=0.1812
# fold_scores for c=0.0005: [ 0.1667  0.1562  0.1667  0.1875  0.2292] mean=0.1812
# fold_scores for c=0.0001: [ 0.1562  0.1458  0.1458  0.1875  0.2292] mean=0.1729
# fold_scores for c=0.5000: [ 0.1667  0.1562  0.1667  0.1875  0.2292] mean=0.1812
# fold_scores for c=1.0000: [ 0.1667  0.1562  0.1667  0.1875  0.2292] mean=0.1812
# fold_scores for c=2.0000: [ 0.1667  0.1562  0.1667  0.1875  0.2292] mean=0.1812
# best c=0.01 with score 0.18125
# linear_svc results for fold {'train': ['P01', 'P04', 'P06', 'P07', 'P11', 'P12', 'P13', 'P14'], 'valid': ['P09']}
#              precision    recall  f1-score   support

#           0       0.75      0.60      0.67         5
#           1       0.15      0.40      0.22         5
#           2       0.33      0.40      0.36         5
#           3       0.29      0.40      0.33         5
#           4       0.33      0.20      0.25         5
#           5       0.50      0.20      0.29         5
#           6       0.00      0.00      0.00         5
#           7       0.20      0.20      0.20         5
#           8       0.00      0.00      0.00         5
#           9       0.33      0.20      0.25         5
#          10       0.40      0.40      0.40         5
#          11       0.50      0.40      0.44         5

# avg / total       0.32      0.28      0.28        60

# [[3 2 0 0 0 0 0 0 0 0 0 0]
#  [0 2 0 0 0 0 0 0 0 1 2 0]
#  [0 0 2 0 0 0 0 1 1 0 1 0]
#  [0 1 0 2 0 0 0 1 1 0 0 0]
#  [1 1 0 0 1 1 0 0 0 0 0 1]
#  [0 1 0 1 1 1 1 0 0 0 0 0]
#  [0 0 2 0 0 0 0 2 1 0 0 0]
#  [0 1 0 3 0 0 0 1 0 0 0 0]
#  [0 2 0 1 1 0 0 0 0 0 0 1]
#  [0 2 0 0 0 0 1 0 1 1 0 0]
#  [0 1 2 0 0 0 0 0 0 0 2 0]
#  [0 0 0 0 0 0 1 0 1 1 0 2]]
# overall test accuracy so far: 0.19
# processing outer fold {'train': ['P01', 'P04', 'P06', 'P07', 'P09', 'P12', 'P13', 'P14'], 'valid': ['P11']}
# fold_scores for c=0.0100: [ 0.1771  0.1562  0.125   0.1875  0.2188] mean=0.1729
# fold_scores for c=0.0500: [ 0.1771  0.1562  0.125   0.1875  0.2188] mean=0.1729
# fold_scores for c=0.1000: [ 0.1771  0.1562  0.125   0.1875  0.2188] mean=0.1729
# fold_scores for c=0.0050: [ 0.1771  0.1562  0.125   0.1875  0.2188] mean=0.1729
# fold_scores for c=0.0010: [ 0.1771  0.1562  0.125   0.1875  0.2188] mean=0.1729
# fold_scores for c=0.0005: [ 0.1771  0.1562  0.125   0.1875  0.2188] mean=0.1729
# fold_scores for c=0.0001: [ 0.1875  0.1562  0.1458  0.1979  0.2292] mean=0.1833
# fold_scores for c=0.5000: [ 0.1771  0.1562  0.125   0.1875  0.2188] mean=0.1729
# fold_scores for c=1.0000: [ 0.1771  0.1562  0.125   0.1875  0.2188] mean=0.1729
# fold_scores for c=2.0000: [ 0.1771  0.1562  0.125   0.1875  0.2188] mean=0.1729
# best c=0.0001 with score 0.183333333333
# linear_svc results for fold {'train': ['P01', 'P04', 'P06', 'P07', 'P09', 'P12', 'P13', 'P14'], 'valid': ['P11']}
#              precision    recall  f1-score   support

#           0       0.00      0.00      0.00         5
#           1       0.50      0.20      0.29         5
#           2       0.00      0.00      0.00         5
#           3       0.20      0.40      0.27         5
#           4       0.20      0.20      0.20         5
#           5       0.00      0.00      0.00         5
#           6       0.00      0.00      0.00         5
#           7       0.00      0.00      0.00         5
#           8       0.00      0.00      0.00         5
#           9       0.00      0.00      0.00         5
#          10       0.00      0.00      0.00         5
#          11       0.12      0.20      0.15         5

# avg / total       0.09      0.08      0.08        60

# [[0 0 2 2 0 1 0 0 0 0 0 0]
#  [0 1 0 0 0 3 0 0 1 0 0 0]
#  [0 0 0 0 2 1 0 0 0 0 2 0]
#  [0 0 0 2 0 0 0 2 0 0 1 0]
#  [0 1 0 0 1 0 0 0 0 0 0 3]
#  [0 0 1 2 0 0 0 0 0 0 1 1]
#  [0 0 0 0 1 0 0 2 0 0 0 2]
#  [0 0 1 2 0 0 0 0 0 0 1 1]
#  [0 0 0 0 0 0 2 0 0 2 1 0]
#  [0 0 2 0 1 2 0 0 0 0 0 0]
#  [0 0 1 2 0 0 1 0 0 1 0 0]
#  [0 0 0 0 0 0 1 1 1 1 0 1]]
# overall test accuracy so far: 0.172222222222
# processing outer fold {'train': ['P01', 'P04', 'P06', 'P07', 'P09', 'P11', 'P13', 'P14'], 'valid': ['P12']}
# fold_scores for c=0.0100: [ 0.1667  0.2083  0.1458  0.2083  0.2604] mean=0.1979
# fold_scores for c=0.0500: [ 0.1667  0.2083  0.1458  0.2083  0.2604] mean=0.1979
# fold_scores for c=0.1000: [ 0.1667  0.2083  0.1458  0.2083  0.2604] mean=0.1979
# fold_scores for c=0.0050: [ 0.1667  0.2083  0.1458  0.2083  0.2604] mean=0.1979
# fold_scores for c=0.0010: [ 0.1667  0.2083  0.1458  0.2083  0.2604] mean=0.1979
# fold_scores for c=0.0005: [ 0.1667  0.2083  0.1458  0.2083  0.2604] mean=0.1979
# fold_scores for c=0.0001: [ 0.1875  0.2292  0.1458  0.2083  0.2396] mean=0.2021
# fold_scores for c=0.5000: [ 0.1667  0.2083  0.1458  0.2083  0.2604] mean=0.1979
# fold_scores for c=1.0000: [ 0.1667  0.2083  0.1458  0.2083  0.2604] mean=0.1979
# fold_scores for c=2.0000: [ 0.1667  0.2083  0.1458  0.2083  0.2604] mean=0.1979
# best c=0.0001 with score 0.202083333333
# linear_svc results for fold {'train': ['P01', 'P04', 'P06', 'P07', 'P09', 'P11', 'P13', 'P14'], 'valid': ['P12']}
#              precision    recall  f1-score   support

#           0       0.25      0.20      0.22         5
#           1       0.33      0.20      0.25         5
#           2       0.14      0.20      0.17         5
#           3       0.00      0.00      0.00         5
#           4       0.50      0.20      0.29         5
#           5       0.25      0.20      0.22         5
#           6       0.33      0.60      0.43         5
#           7       0.00      0.00      0.00         5
#           8       0.22      0.40      0.29         5
#           9       0.12      0.20      0.15         5
#          10       0.00      0.00      0.00         5
#          11       0.67      0.40      0.50         5

# avg / total       0.24      0.22      0.21        60

# [[1 0 1 1 0 1 0 0 1 0 0 0]
#  [0 1 1 0 0 1 1 0 0 1 0 0]
#  [0 0 1 0 1 0 2 0 1 0 0 0]
#  [1 0 0 0 0 0 0 1 2 1 0 0]
#  [0 0 1 0 1 0 0 1 1 1 0 0]
#  [0 0 0 0 0 1 1 0 0 1 1 1]
#  [0 0 0 0 0 0 3 2 0 0 0 0]
#  [1 0 0 0 0 0 0 0 1 2 1 0]
#  [0 0 0 0 0 1 1 0 2 1 0 0]
#  [0 1 1 2 0 0 0 0 0 1 0 0]
#  [1 1 2 1 0 0 0 0 0 0 0 0]
#  [0 0 0 0 0 0 1 0 1 0 1 2]]
# overall test accuracy so far: 0.178571428571
# processing outer fold {'train': ['P01', 'P04', 'P06', 'P07', 'P09', 'P11', 'P12', 'P14'], 'valid': ['P13']}
# fold_scores for c=0.0100: [ 0.1979  0.1875  0.2188  0.1771  0.2292] mean=0.2021
# fold_scores for c=0.0500: [ 0.1979  0.1875  0.2188  0.1771  0.2292] mean=0.2021
# fold_scores for c=0.1000: [ 0.1979  0.1875  0.2188  0.1771  0.2292] mean=0.2021
# fold_scores for c=0.0050: [ 0.1979  0.1875  0.2188  0.1771  0.2292] mean=0.2021
# fold_scores for c=0.0010: [ 0.1979  0.1875  0.2188  0.1771  0.2292] mean=0.2021
# fold_scores for c=0.0005: [ 0.1979  0.1875  0.2188  0.1771  0.2292] mean=0.2021
# fold_scores for c=0.0001: [ 0.1979  0.1875  0.1979  0.1875  0.2292] mean=0.2000
# fold_scores for c=0.5000: [ 0.1979  0.1875  0.2188  0.1771  0.2292] mean=0.2021
# fold_scores for c=1.0000: [ 0.1979  0.1875  0.2188  0.1771  0.2292] mean=0.2021
# fold_scores for c=2.0000: [ 0.1979  0.1875  0.2188  0.1771  0.2292] mean=0.2021
# best c=0.01 with score 0.202083333333
# linear_svc results for fold {'train': ['P01', 'P04', 'P06', 'P07', 'P09', 'P11', 'P12', 'P14'], 'valid': ['P13']}
#              precision    recall  f1-score   support

#           0       0.00      0.00      0.00         5
#           1       0.20      0.40      0.27         5
#           2       0.17      0.20      0.18         5
#           3       0.14      0.20      0.17         5
#           4       1.00      0.20      0.33         5
#           5       0.00      0.00      0.00         5
#           6       0.14      0.20      0.17         5
#           7       0.00      0.00      0.00         5
#           8       0.50      0.40      0.44         5
#           9       0.50      0.60      0.55         5
#          10       0.00      0.00      0.00         5
#          11       0.00      0.00      0.00         5

# avg / total       0.22      0.18      0.18        60

# [[0 1 0 1 0 1 1 0 0 0 0 1]
#  [0 2 0 2 0 0 0 0 1 0 0 0]
#  [0 0 1 0 0 1 1 0 0 1 1 0]
#  [0 0 1 1 0 0 0 1 0 1 0 1]
#  [0 0 0 1 1 0 0 0 1 0 1 1]
#  [1 1 1 1 0 0 0 0 0 1 0 0]
#  [0 1 1 0 0 1 1 0 0 0 0 1]
#  [1 3 1 0 0 0 0 0 0 0 0 0]
#  [1 0 0 0 0 1 0 0 2 0 0 1]
#  [0 0 0 0 0 0 1 0 0 3 1 0]
#  [0 2 0 0 0 0 2 0 0 0 0 1]
#  [0 0 1 1 0 0 1 0 0 0 2 0]]
# overall test accuracy so far: 0.179166666667
# processing outer fold {'train': ['P01', 'P04', 'P06', 'P07', 'P09', 'P11', 'P12', 'P13'], 'valid': ['P14']}
# fold_scores for c=0.0100: [ 0.1979  0.2292  0.1771  0.1562  0.1875] mean=0.1896
# fold_scores for c=0.0500: [ 0.1979  0.2292  0.1771  0.1562  0.1875] mean=0.1896
# fold_scores for c=0.1000: [ 0.1979  0.2292  0.1771  0.1562  0.1875] mean=0.1896
# fold_scores for c=0.0050: [ 0.1979  0.2292  0.1771  0.1562  0.1875] mean=0.1896
# fold_scores for c=0.0010: [ 0.1979  0.2292  0.1771  0.1562  0.1875] mean=0.1896
# fold_scores for c=0.0005: [ 0.1979  0.2292  0.1771  0.1562  0.1875] mean=0.1896
# fold_scores for c=0.0001: [ 0.1979  0.2292  0.1458  0.1771  0.2188] mean=0.1938
# fold_scores for c=0.5000: [ 0.1979  0.2292  0.1771  0.1562  0.1875] mean=0.1896
# fold_scores for c=1.0000: [ 0.1979  0.2292  0.1771  0.1562  0.1875] mean=0.1896
# fold_scores for c=2.0000: [ 0.1979  0.2292  0.1771  0.1562  0.1875] mean=0.1896
# best c=0.0001 with score 0.19375
# linear_svc results for fold {'train': ['P01', 'P04', 'P06', 'P07', 'P09', 'P11', 'P12', 'P13'], 'valid': ['P14']}
#              precision    recall  f1-score   support

#           0       0.29      0.40      0.33         5
#           1       0.12      0.20      0.15         5
#           2       0.29      0.40      0.33         5
#           3       0.00      0.00      0.00         5
#           4       0.33      0.20      0.25         5
#           5       0.33      0.40      0.36         5
#           6       0.20      0.20      0.20         5
#           7       0.00      0.00      0.00         5
#           8       0.33      0.60      0.43         5
#           9       0.00      0.00      0.00         5
#          10       0.00      0.00      0.00         5
#          11       0.40      0.40      0.40         5

# avg / total       0.19      0.23      0.21        60

# [[2 0 1 0 0 0 1 1 0 0 0 0]
#  [0 1 0 1 0 1 0 1 0 0 0 1]
#  [0 0 2 0 0 0 1 1 1 0 0 0]
#  [0 1 0 0 1 2 0 0 0 0 0 1]
#  [0 0 2 0 1 0 0 0 0 2 0 0]
#  [1 1 0 0 0 2 0 0 1 0 0 0]
#  [0 0 0 0 1 0 1 0 2 1 0 0]
#  [1 1 0 1 0 1 1 0 0 0 0 0]
#  [1 1 0 0 0 0 0 0 3 0 0 0]
#  [0 2 0 0 0 0 0 0 2 0 1 0]
#  [1 1 1 0 0 0 0 0 0 1 0 1]
#  [1 0 1 0 0 0 1 0 0 0 0 2]]
# overall test accuracy so far: 0.185185185185
# all folds completed

# SUMMARY for classifier linear_svc

# fold scores:  [ 0.25    0.1833  0.1     0.1333  0.2833  0.0833  0.2167  0.1833  0.2333]

#              precision    recall  f1-score   support

#         0.0       0.19      0.16      0.17        45
#         1.0       0.18      0.22      0.20        45
#         2.0       0.17      0.20      0.18        45
#         3.0       0.16      0.18      0.17        45
#         4.0       0.26      0.18      0.21        45
#         5.0       0.18      0.13      0.15        45
#         6.0       0.19      0.22      0.20        45
#         7.0       0.13      0.11      0.12        45
#         8.0       0.22      0.29      0.25        45
#         9.0       0.19      0.18      0.18        45
#        10.0       0.10      0.09      0.09        45
#        11.0       0.26      0.27      0.26        45

# avg / total       0.19      0.19      0.18       540

# [[ 7  4  7  5  3  4  6  1  1  1  1  5]
#  [ 1 10  1  7  0  6  1  4  5  3  6  1]
#  [ 3  1  9  1  3  4  5  3  5  3  8  0]
#  [ 1  3  2  8  5  2  2  7  4  4  2  5]
#  [ 5  3  4  3  8  2  1  2  5  4  2  6]
#  [ 5  8  3  6  1  6  3  2  3  3  2  3]
#  [ 1  2  5  1  3  2 10  7  6  1  2  5]
#  [ 5  5  4  8  1  3  3  5  3  4  3  1]
#  [ 2  5  2  1  3  2  6  1 13  5  2  3]
#  [ 0 10  5  3  2  2  3  2  5  8  5  0]
#  [ 3  6 10  4  0  1  5  1  3  3  4  5]
#  [ 3  0  2  2  2  0  8  3  5  3  5 12]]

# train accuracy: 0.999074074074
# test accuracy : 0.185185185185